# Generated by Django 2.2.8 on 2019-12-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'producers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('expiration_date', models.DateField(null=True)),
                ('dangerous', models.BooleanField(default=False)),
                ('storage', models.CharField(choices=[('n', 'Normal'), ('c', 'Fridge'), ('f', 'Freezer'), ('o', 'Other')], max_length=1)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.Producer')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('area', models.PositiveIntegerField()),
                ('externalOwner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.Warehouse')),
            ],
        ),
    ]
