# Generated by Django 2.2.8 on 2019-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20191226_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='externalOwner',
            field=models.BooleanField(default=False),
        ),
    ]
